total_shutdown_timeout:
  15s

http_server:
  port: 5002
  cors:
    allow_origins: "*"
  shutdown_context_timeout: "10s"


logger:
  file_path: "logs/user/service.log"
  use_local_time: true
  file_max_size_in_mb: 10
  file_max_age_in_days: 7

