services:
  vectorlayer-db:
    image: postgres:17.2-alpine
    environment:
      - 'POSTGRES_DB=vectorlayer_db'
      - 'POSTGRES_USER=vectorlayer_admin'
      - 'POSTGRES_PASSWORD=password123'
    restart: always
    profiles:
      - vectorlayer
    ports:
      - "5434:5432"

  vectorlayer-redis:
    image: redis:8.0-M03-alpine3.21
    restart: always
    command: redis-server --loglevel warning --protected-mode no --save "" --appendonly no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    profiles:
      - vectorlayer

  vectorlayer-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GO_IMAGE_NAME: ${GO_IMAGE_NAME}
        GO_IMAGE_VERSION: ${GO_IMAGE_VERSION}
    image: ${SERVICE_NAME}-vectorlayer:${GO_IMAGE_NAME}-${GO_IMAGE_VERSION}
    env_file:
      - .env
    entrypoint:
      - air
      - "-c"
      - /home/app/.air/.air.vectorlayer.toml
    volumes:
      - ./:/home/app
    profiles:
      - vectorlayer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}_vectorlayer.service=${SERVICE_NAME}_vectorlayer"
      - "traefik.http.routers.${SERVICE_NAME}_vectorlayer.rule=Host(`${SERVICE_DOMAIN}`)&&PathPrefix(`/vectorlayer`)"
      - "traefik.http.routers.${SERVICE_NAME}_vectorlayer.middlewares=${SERVICE_NAME}_strip_vectorlayer"
      - "traefik.http.routers.${SERVICE_NAME}_vectorlayer.entrypoints=web"
      - "traefik.http.services.${SERVICE_NAME}_vectorlayer.loadbalancer.server.port=5002"
      - "traefik.http.middlewares.${SERVICE_NAME}_strip_vectorlayer.stripprefix.prefixes=/vectorlayer"
