services:
  filer-service:
    build:
      context: .
      dockerfile: ./deploy/filer/development/Dockerfile
      args:
        GO_IMAGE_NAME: ${GO_IMAGE_NAME}
        GO_IMAGE_VERSION: ${GO_IMAGE_VERSION}
    image: ${SERVICE_NAME}-filer:${GO_IMAGE_NAME}-${GO_IMAGE_VERSION}
    env_file:
      - ./deploy/.env
    entrypoint:
      - go
      - run
      - 'cmd/filer/main.go'
      - serve
    volumes:
      - ./:/home/app
    profiles:
      - filer
    ports:
      - "5005:5005"
      - "5006:5006"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}_filer.service=${SERVICE_NAME}_filer"
      - "traefik.http.routers.${SERVICE_NAME}_filer.rule=Host(`${SERVICE_DOMAIN}`)&&PathPrefix(`/filer`)"
      - "traefik.http.routers.${SERVICE_NAME}_filer.entrypoints=web"
      - "traefik.http.services.${SERVICE_NAME}_filer.loadbalancer.server.port=5005"
      - "traefik.http.routers.${SERVICE_NAME}_filer.middlewares=${SERVICE_NAME}_strip_filer"
      - "traefik.http.middlewares.${SERVICE_NAME}_strip_filer.stripprefix.prefixes=/filer"
    environment:
      ENV: "development"
  filer-db:
    image: postgres:17.2-alpine
    environment:
      - 'POSTGRES_DB=filer_db'
      - 'POSTGRES_USER=roham'
      - 'POSTGRES_PASSWORD=secret'
    restart: always
    profiles:
      - filer
    ports:
      - "5433:5432"
#  minio:
#    image: minio/minio:latest
#    environment:
#      - MINIO_ROOT_USER=minioadmin
#      - MINIO_ROOT_PASSWORD=minioadmin
#    volumes:
#      - minio-data:/data
#    command: server /data --console-address ":9001"
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#    profiles:
#      - filer
#volumes:
#  minio-data: