services:
  user-db:
    image: postgres:17.2-alpine
    environment:
      - 'POSTGRES_DB=user_db'
      - 'POSTGRES_USER=user_admin'
      - 'POSTGRES_PASSWORD=password123'
    restart: always
    profiles:
      - user
    ports:
      - "5433:5432"

  user-redis:
    image: redis:8.0-M03-alpine3.21
    restart: always
    command: redis-server --loglevel warning --protected-mode no --save "" --appendonly no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    profiles:
      - user

  user-service:
    build:
      context: .
      dockerfile: ./deploy/user/development/Dockerfile
      args:
        GO_IMAGE_NAME: ${GO_IMAGE_NAME}
        GO_IMAGE_VERSION: ${GO_IMAGE_VERSION}
    image: ${SERVICE_NAME}-user:${GO_IMAGE_NAME}-${GO_IMAGE_VERSION}
    env_file:
      - .env
    entrypoint:
      - air
      - "-c"
      - /home/app/.air/.air.user.toml
    volumes:
      - ./:/home/app
    profiles:
      - user
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"

      # Routers with authentication
      - "traefik.http.routers.${SERVICE_NAME}_user.service=${SERVICE_NAME}_user"
      - "traefik.http.routers.${SERVICE_NAME}_user.rule=Host(`${SERVICE_DOMAIN}`) && PathPrefix(`/users`)"
      - "traefik.http.routers.${SERVICE_NAME}_user.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}_user.middlewares=roham_auth@file,roham_authz@file,${SERVICE_NAME}_strip_user"
      - "traefik.http.services.${SERVICE_NAME}_user.loadbalancer.server.port=5001"

      # Routers without authentication
      - "traefik.http.routers.${SERVICE_NAME}_user_no_auth.service=${SERVICE_NAME}_user"
      - "traefik.http.routers.${SERVICE_NAME}_user_no_auth.rule=Host(`${SERVICE_DOMAIN}`) && (
          PathPrefix(`/users/v1/health-check`) ||
          PathPrefix(`/users/v1/users/login`))"
      - "traefik.http.routers.${SERVICE_NAME}_user_no_auth.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}_user_no_auth.middlewares=${SERVICE_NAME}_strip_user"

      # Middleware for stripping /users prefix
      - "traefik.http.middlewares.${SERVICE_NAME}_strip_user.stripprefix.prefixes=/users"

